
#Site settings
title: Rebecca Colquhoun
email: rebecca.colquhoun[at]univ.ox.ac.uk
#description: Rebecca Colquhoun's personal website
twitter_username: RebeccaC13
base-url: rebeccacolquhoun.github.io


#Build settings
Markdown: kramdown
theme: academic
gems:
 - Jekyll-feed

theme: minima
