
#Site settings
Title: Rebecca Colquhoun
Email: Rebecca.colquhoun@univ.ox.ac.uk
Description: Rebecca Colquhoun's personal website
twitter_username: RebeccaC13
Base-url: rebeccacolquhoun.github.io
site-name: Rebecca Colquhoun
site.name: Rebecca Colquhoun
site.title: Rebecca Colquhoun
Name: Rebecca Colquhoun

#Build settings
Markdown: kramdown
Theme: Slate
Gems:
 - Jekyll-feed

theme: minima
