
#Site settings
title: Rebecca Colquhoun
email: rebecca.colquhoun@univ.ox.ac.uk
#description: Rebecca Colquhoun's personal website
twitter_username: RebeccaC13
mastodon: <a rel="me" href="https://mstdn.social/@Colquhoun">Mastodon</a>
base-url: rebeccacolquhoun.github.io


#Build settings
Markdown: kramdown
theme: academic
gems:
 - Jekyll-feed

theme: minima
